name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Manually Write .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check .npmrc
        run: cat ~/.npmrc

      - name: Force HTTPS for Git Dependencies
        run: git config --global url."git+https://github.com/".insteadOf "git+ssh://git@github.com/"

      - name: Set GitHub Authentication
        run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
