name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Publish Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder build --publish always
