name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # ✅ 允许手动触发

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
env:
  ELECTRON_MIRROR: 'https://npmmirror.com/mirrors/electron/'
